### ISSUE TITLE
[Bug] Swagger doc, response decorator, arguments possibly misaligned.

### ISSUE THREAD

**Issue by kevayacht** [huge-success/sanic-openapi#144]
**Describe the bug**
It appears that when the doc.response decorator is used to document the possible responses, basically for the swagger documentation, 
A clear and concise description of what the bug is. It there is error log, please provide it.

**Screenshots**
No screenshots are included as it will not actually help and is thus not necessary. 

**To Reproduce**
Here follows a short script to quickly reproduce the issue:

A basic setup is all that is necessary, adding in a doc.response decorator with a description field following the status code will result in a IndexError.

`
from sanic import Sanic
from sanic.response import json
from sanic_openapi import swagger_blueprint, doc

app = Sanic()
app.blueprint(swagger_blueprint)

@app.route("/")
@doc.response(404, description="This is the description of the response code")
async def test(request):
    return json({"hello": "world"})

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=8000)    #  locathost
`

I am not completely sure what the intention was in the code highlighted by the below error, but is seems that the RouteField class is expecting an additional arg, namely the variable "field" - when looking into the sanic_openapi.doc code. If that variable was not intentionally assigned as such, it would probably make sense to assign a default value to it as well, and not pass in the args[1] to the RouteField class. 

`
Traceback (most recent call last):
  File "test_api.py", line 10, in <module>
    @doc.response(404, description="This is the description of the response code")
  File "/path/to/project/venv/lib/python3.7/site-packages/sanic_openapi/doc.py", line 324, in inner
    routefield = RouteField(args[1], description=description)
IndexError: tuple index out of range
`
Note: I just anonymized my file path.

**Expected behavior**
Expected a description field to have been added to the swagger.json under the response documentation. This obviously does not happen.

**Current Workaround**
This is just a code snippet, note the additional arg passed to the doc.response decorator.

`
from sanic import Sanic
from sanic.response import json
from sanic_openapi import swagger_blueprint, doc

app = Sanic()
app.blueprint(swagger_blueprint)

@app.route("/")
@doc.response(404, "", description="This is the description of the response code")
async def test(request):
    return json({"hello": "world"})

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=8000)   #  locathost
`

**Environment**
 - OS: macOS Catalina, 10.15.1
 - Browser : Chrome 
 - Version: 0.6.0 (2019-08-02)
- Virtual Environment with Python 3.7 

**Additional context**
I found this slight issue setting up some "client" facing swagger documentation. Hilarious that dev's need documentation right? Either way this is by no means a large issue, and is easily circumvented by adding a dummy arg as a placeholder as shown above, but hey, every bit helps :).

This can probably be easily fixed. I will also probably submit a pull request for this issue.

**Comment by kevayacht** [comment]
nevermind - read the docs.
