### ISSUE TITLE
Bug version 0.5.0

### ISSUE THREAD

**Issue by raphaelauv** [huge-success/sanic-openapi#85]
Hello ! , thank for all your job 

unfortunately your last big version do not work with sanic 18.12.0

I have theses Exceptions : 

`ERROR:sanic.root:Exception occurred while handling uri: 'http://localhost:8000/swagger-ui.css'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 736, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/usr/local/lib/python3.6/site-packages/sanic/router.py", line 396, in get
    return self._get(request.path, request.method, "")
  File "/usr/local/lib/python3.6/site-packages/sanic/router.py", line 458, in _get
    raise NotFound("Requested URL {} not found".format(url))

sanic.exceptions.NotFound: Requested URL /swagger-ui.css not found

[2019-04-02 13:53:19 +0000] - (sanic.access)[INFO][10.102.52.1:40210]: GET http://localhost:8000/swagger-ui.css  404 46

INFO:sanic.access:
[2019-04-02 13:53:19 +0000] [1] [ERROR] Exception occurred while handling uri: 'http://localhost:8000/swagger-ui-bundle.js'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 736, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/usr/local/lib/python3.6/site-packages/sanic/router.py", line 396, in get
    return self._get(request.path, request.method, "")
  File "/usr/local/lib/python3.6/site-packages/sanic/router.py", line 458, in _get

ERROR:sanic.root:Exception occurred while handling uri: 'http://localhost:8000/swagger-ui-bundle.js'`

Should I rollback to 0.4.0 ?

thank you again

**Comment by chenjr0719** [comment]
Did you use `/swaager` endpoint? It a know issue, you can check #85 and #22 for more information. This would be fix after merge #83.

**Comment by raphaelauv** [comment]
Hey thank for your answer , yes I was using /swagger endpoint , is there another endpoint while the #83 is not merged ? 

Thank again

**Comment by ahopkins** [comment]
#83 is merged

**Comment by raphaelauv** [comment]
Many thanks !!

Will you update the actual release or create a new one ?
