### ISSUE TITLE
TypeError: Object of type type is not JSON serializable

### ISSUE THREAD

**Issue by pytomtoto** [huge-success/sanic-openapi#90]
models
```
class ModelsDemo:
    id = int
    name = str
    version = str
    type = str
    installation_path = str

```
views
```
blueprint = Blueprint('demo', '/demo')


@blueprint.get("/", strict_slashes=True)
@doc.summary("demo")
@doc.consumes(ModelsDemo, location="body")
async def ModelsDemoViews(request, *args, **kwargs):
    """
    List
    """
    pass
```
errors
```
[2019-04-22 16:35:44 +0800] [44224] [ERROR] Exception occurred while handling uri: 'http://127.0.0.1:8080/swagger/swagger.json'
Traceback (most recent call last):
  File "E:\code\alter_svc\websocket-svc\lib\site-packages\sanic\app.py", line 915, in handle_request
    response = handler(request, *args, **kwargs)
  File "E:\local_git\fund-slb-svc\sanic_openapi\swagger.py", line 208, in spec
    return json(_spec)
  File "E:\code\alter_svc\websocket-svc\lib\site-packages\sanic\response.py", line 220, in json
    dumps(body, **kwargs),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type type is not JSON serializable
```

> python version 3.7
sanic version 19.3.1
sanic-openapi version 0.5.1

**Comment by pytomtoto** [comment]
It's  work
```
@doc.consumes(doc.JsonBody({
    "id": int,
    "name": str,
    "version": str,
    "type": str,
    "installation_path": str
}), location="body")
```
